#include "unlock.h"

void all_gpio_pin_unlock(void){
	//PA2-PA5的解锁
  ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
	HWREG(GPIO_PORTA_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_LOCKED;
	HWREG(GPIO_PORTA_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
  HWREG(GPIO_PORTA_BASE + GPIO_O_CR) |= 0x3c;
 // HWREG(GPIO_PORTA_BASE + GPIO_O_LOCK) = 0;
	
	
	//PB2-PB3
	ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
	HWREG(GPIO_PORTA_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_LOCKED;
	HWREG(GPIO_PORTA_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_KEY; 
	HWREG(GPIO_PORTA_BASE+GPIO_O_CR)   =0x0C;
	
	//PD7按键
	ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
	HWREG(GPIO_PORTD_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_LOCKED;
	HWREG(GPIO_PORTD_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_KEY; 
	HWREG(GPIO_PORTD_BASE+GPIO_O_CR)   =0x80;
	
	
	//pf4 pf0解锁,超声波的引脚
	ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
	HWREG(GPIO_PORTF_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_LOCKED;
	HWREG(GPIO_PORTF_BASE+GPIO_O_LOCK)  |= GPIO_LOCK_KEY; 
	HWREG(GPIO_PORTF_BASE+GPIO_O_CR)   =0x11;
	
	
	
	
	
	
}
